print('==================================================')
require "headphone.headphone"
require "hotkey.hotkey"
require "reload.reload"
require "usb.usb"
require "wifi.wifi"
require "window.window"
-- require "clipboard.clipboard"
require "volume.volume"
require "clipboard.an-clipboard"
require "switcher.switcher"
require "screen.screen"
require "clock.clock"
